project_name: clank

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - COSIGN_YES=true

# Prevents parallel builds from stepping on each others toes downloading modules
before:
  hooks:
    - go mod tidy
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

gomod:
  proxy: true

sboms:
  - artifacts: binary

builds:
  - id: clank
    binary: clank-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    main: .
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '7'
    env:
      - CGO_ENABLED=0

signs:
  # Keyless
  - id: clank
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}.sig", "--output-certificate", "${artifact}.pem", "${artifact}"]
    artifacts: binary
  - id: checksum
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}.sig", "--output-certificate", "${artifact}.pem", "${artifact}"]
    artifacts: checksum

kos:
  - id: clank
    main: .
    working_dir: .
    base_image: cgr.dev/chainguard/static:latest
    repository: ghcr.io/chainguard-dev/clank
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - latest
      - '{{.Tag}}'
    creation_time: '{{.CommitTimestamp}}'
    ko_data_creation_time: '{{.CommitTimestamp}}'
    ldflags:
      - -extldflags "-static"
    flags:
      - -trimpath
    preserve_import_paths: false
    base_import_paths: false
    bare: true

docker_signs:
  - artifacts: manifests
    args:
      - "sign"
      - "${artifact}"

archives:
  - format: binary
    name_template: "{{ .Binary }}"
    allow_different_binary_count: true

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

release:
  draft: true
  github:
    owner: chainguard-dev
    name: clank
